on:
    schedule:
      - cron: '0 */6 * * *'
    workflow_dispatch:
jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - name: Fetch feeds
        working-directory: src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python fetch.py
