# Run on schedule
# minus 2 hours with GMT+1
on:
    schedule:
      - cron: '0 5,10,17 * * *'
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Check out repository code
      - name: Set cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip|${{ hashFiles('src/requirements.txt') }}
      - name: Fetch feeds
        run: |
          pip install -r src/requirements.txt
          python src/fetch.py
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
